server:
  http:
    addr: 127.0.0.1:8001
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
auth:
  secret: "kratos-http-app"
  expire: 3600s
trace:
  endpoint: 127.0.0.1:4317