// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"kratos-project/app/grpc_user/internal/data/ent/predicate"
	"kratos-project/app/grpc_user/internal/data/ent/userinfo"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserInfoQuery is the builder for querying UserInfo entities.
type UserInfoQuery struct {
	config
	ctx        *QueryContext
	order      []userinfo.OrderOption
	inters     []Interceptor
	predicates []predicate.UserInfo
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserInfoQuery builder.
func (uiq *UserInfoQuery) Where(ps ...predicate.UserInfo) *UserInfoQuery {
	uiq.predicates = append(uiq.predicates, ps...)
	return uiq
}

// Limit the number of records to be returned by this query.
func (uiq *UserInfoQuery) Limit(limit int) *UserInfoQuery {
	uiq.ctx.Limit = &limit
	return uiq
}

// Offset to start from.
func (uiq *UserInfoQuery) Offset(offset int) *UserInfoQuery {
	uiq.ctx.Offset = &offset
	return uiq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (uiq *UserInfoQuery) Unique(unique bool) *UserInfoQuery {
	uiq.ctx.Unique = &unique
	return uiq
}

// Order specifies how the records should be ordered.
func (uiq *UserInfoQuery) Order(o ...userinfo.OrderOption) *UserInfoQuery {
	uiq.order = append(uiq.order, o...)
	return uiq
}

// First returns the first UserInfo entity from the query.
// Returns a *NotFoundError when no UserInfo was found.
func (uiq *UserInfoQuery) First(ctx context.Context) (*UserInfo, error) {
	nodes, err := uiq.Limit(1).All(setContextOp(ctx, uiq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{userinfo.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (uiq *UserInfoQuery) FirstX(ctx context.Context) *UserInfo {
	node, err := uiq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserInfo ID from the query.
// Returns a *NotFoundError when no UserInfo ID was found.
func (uiq *UserInfoQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uiq.Limit(1).IDs(setContextOp(ctx, uiq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{userinfo.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (uiq *UserInfoQuery) FirstIDX(ctx context.Context) int {
	id, err := uiq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserInfo entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserInfo entity is found.
// Returns a *NotFoundError when no UserInfo entities are found.
func (uiq *UserInfoQuery) Only(ctx context.Context) (*UserInfo, error) {
	nodes, err := uiq.Limit(2).All(setContextOp(ctx, uiq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{userinfo.Label}
	default:
		return nil, &NotSingularError{userinfo.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (uiq *UserInfoQuery) OnlyX(ctx context.Context) *UserInfo {
	node, err := uiq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserInfo ID in the query.
// Returns a *NotSingularError when more than one UserInfo ID is found.
// Returns a *NotFoundError when no entities are found.
func (uiq *UserInfoQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uiq.Limit(2).IDs(setContextOp(ctx, uiq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{userinfo.Label}
	default:
		err = &NotSingularError{userinfo.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (uiq *UserInfoQuery) OnlyIDX(ctx context.Context) int {
	id, err := uiq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserInfos.
func (uiq *UserInfoQuery) All(ctx context.Context) ([]*UserInfo, error) {
	ctx = setContextOp(ctx, uiq.ctx, ent.OpQueryAll)
	if err := uiq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UserInfo, *UserInfoQuery]()
	return withInterceptors[[]*UserInfo](ctx, uiq, qr, uiq.inters)
}

// AllX is like All, but panics if an error occurs.
func (uiq *UserInfoQuery) AllX(ctx context.Context) []*UserInfo {
	nodes, err := uiq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserInfo IDs.
func (uiq *UserInfoQuery) IDs(ctx context.Context) (ids []int, err error) {
	if uiq.ctx.Unique == nil && uiq.path != nil {
		uiq.Unique(true)
	}
	ctx = setContextOp(ctx, uiq.ctx, ent.OpQueryIDs)
	if err = uiq.Select(userinfo.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (uiq *UserInfoQuery) IDsX(ctx context.Context) []int {
	ids, err := uiq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (uiq *UserInfoQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, uiq.ctx, ent.OpQueryCount)
	if err := uiq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, uiq, querierCount[*UserInfoQuery](), uiq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (uiq *UserInfoQuery) CountX(ctx context.Context) int {
	count, err := uiq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (uiq *UserInfoQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, uiq.ctx, ent.OpQueryExist)
	switch _, err := uiq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (uiq *UserInfoQuery) ExistX(ctx context.Context) bool {
	exist, err := uiq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserInfoQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (uiq *UserInfoQuery) Clone() *UserInfoQuery {
	if uiq == nil {
		return nil
	}
	return &UserInfoQuery{
		config:     uiq.config,
		ctx:        uiq.ctx.Clone(),
		order:      append([]userinfo.OrderOption{}, uiq.order...),
		inters:     append([]Interceptor{}, uiq.inters...),
		predicates: append([]predicate.UserInfo{}, uiq.predicates...),
		// clone intermediate query.
		sql:  uiq.sql.Clone(),
		path: uiq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Account string `json:"account,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserInfo.Query().
//		GroupBy(userinfo.FieldAccount).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (uiq *UserInfoQuery) GroupBy(field string, fields ...string) *UserInfoGroupBy {
	uiq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserInfoGroupBy{build: uiq}
	grbuild.flds = &uiq.ctx.Fields
	grbuild.label = userinfo.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Account string `json:"account,omitempty"`
//	}
//
//	client.UserInfo.Query().
//		Select(userinfo.FieldAccount).
//		Scan(ctx, &v)
func (uiq *UserInfoQuery) Select(fields ...string) *UserInfoSelect {
	uiq.ctx.Fields = append(uiq.ctx.Fields, fields...)
	sbuild := &UserInfoSelect{UserInfoQuery: uiq}
	sbuild.label = userinfo.Label
	sbuild.flds, sbuild.scan = &uiq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserInfoSelect configured with the given aggregations.
func (uiq *UserInfoQuery) Aggregate(fns ...AggregateFunc) *UserInfoSelect {
	return uiq.Select().Aggregate(fns...)
}

func (uiq *UserInfoQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range uiq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, uiq); err != nil {
				return err
			}
		}
	}
	for _, f := range uiq.ctx.Fields {
		if !userinfo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if uiq.path != nil {
		prev, err := uiq.path(ctx)
		if err != nil {
			return err
		}
		uiq.sql = prev
	}
	return nil
}

func (uiq *UserInfoQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserInfo, error) {
	var (
		nodes = []*UserInfo{}
		_spec = uiq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserInfo).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserInfo{config: uiq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, uiq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (uiq *UserInfoQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := uiq.querySpec()
	_spec.Node.Columns = uiq.ctx.Fields
	if len(uiq.ctx.Fields) > 0 {
		_spec.Unique = uiq.ctx.Unique != nil && *uiq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, uiq.driver, _spec)
}

func (uiq *UserInfoQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(userinfo.Table, userinfo.Columns, sqlgraph.NewFieldSpec(userinfo.FieldID, field.TypeInt))
	_spec.From = uiq.sql
	if unique := uiq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if uiq.path != nil {
		_spec.Unique = true
	}
	if fields := uiq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userinfo.FieldID)
		for i := range fields {
			if fields[i] != userinfo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := uiq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := uiq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := uiq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := uiq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (uiq *UserInfoQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(uiq.driver.Dialect())
	t1 := builder.Table(userinfo.Table)
	columns := uiq.ctx.Fields
	if len(columns) == 0 {
		columns = userinfo.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if uiq.sql != nil {
		selector = uiq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if uiq.ctx.Unique != nil && *uiq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range uiq.predicates {
		p(selector)
	}
	for _, p := range uiq.order {
		p(selector)
	}
	if offset := uiq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := uiq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserInfoGroupBy is the group-by builder for UserInfo entities.
type UserInfoGroupBy struct {
	selector
	build *UserInfoQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (uigb *UserInfoGroupBy) Aggregate(fns ...AggregateFunc) *UserInfoGroupBy {
	uigb.fns = append(uigb.fns, fns...)
	return uigb
}

// Scan applies the selector query and scans the result into the given value.
func (uigb *UserInfoGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uigb.build.ctx, ent.OpQueryGroupBy)
	if err := uigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserInfoQuery, *UserInfoGroupBy](ctx, uigb.build, uigb, uigb.build.inters, v)
}

func (uigb *UserInfoGroupBy) sqlScan(ctx context.Context, root *UserInfoQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(uigb.fns))
	for _, fn := range uigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*uigb.flds)+len(uigb.fns))
		for _, f := range *uigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*uigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserInfoSelect is the builder for selecting fields of UserInfo entities.
type UserInfoSelect struct {
	*UserInfoQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (uis *UserInfoSelect) Aggregate(fns ...AggregateFunc) *UserInfoSelect {
	uis.fns = append(uis.fns, fns...)
	return uis
}

// Scan applies the selector query and scans the result into the given value.
func (uis *UserInfoSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uis.ctx, ent.OpQuerySelect)
	if err := uis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserInfoQuery, *UserInfoSelect](ctx, uis.UserInfoQuery, uis, uis.inters, v)
}

func (uis *UserInfoSelect) sqlScan(ctx context.Context, root *UserInfoQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(uis.fns))
	for _, fn := range uis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*uis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
