services:
  consul:
    image: hashicorp/consul
    restart: always
    container_name: consul_server
    networks:
      - local_net
    volumes:
      - /data/consul:/tmp/consul
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8302:8302"
      - "8500:8500"
    command: agent -server -ui -node=n1 -bootstrap-expect=1 -client=0.0.0.0
  db:
    image: mysql:latest
    restart: always
    container_name: mysql_server
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kratos_project
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - /data/db:/var/lib/mysql
  redis:
    image: redis:latest
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /data/redis/data:/root/redis
      - /data/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=123456
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger_server
    restart: always
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      - LOG_LEVEL=debug
      - JAEGER_AGENT_MAX_PACKET_SIZE=65000
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_server
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    volumes:
      - /data/rabbitmq:/var/lib/rabbitmq

networks:
  local_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16