// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.1
// source: mq_consume_user.proto

package mq_consume

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The user service definition.
type MqUserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account  string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`   // 用户账号
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // 用户密码
	Name     string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`         // 用户名称
	Avatar   string `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`     // 用户头像地址
}

func (x *MqUserInfo) Reset() {
	*x = MqUserInfo{}
	mi := &file_mq_consume_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MqUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MqUserInfo) ProtoMessage() {}

func (x *MqUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mq_consume_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MqUserInfo.ProtoReflect.Descriptor instead.
func (*MqUserInfo) Descriptor() ([]byte, []int) {
	return file_mq_consume_user_proto_rawDescGZIP(), []int{0}
}

func (x *MqUserInfo) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *MqUserInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *MqUserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MqUserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

var File_mq_consume_user_proto protoreflect.FileDescriptor

var file_mq_consume_user_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6d, 0x71, 0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x5f, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6d, 0x71, 0x5f, 0x63, 0x6f, 0x6e, 0x73,
	0x75, 0x6d, 0x65, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x6e, 0x0a, 0x0a, 0x4d, 0x71, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61,
	0x72, 0x42, 0x2a, 0x5a, 0x28, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2d, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x71, 0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x75,
	0x6d, 0x65, 0x3b, 0x6d, 0x71, 0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mq_consume_user_proto_rawDescOnce sync.Once
	file_mq_consume_user_proto_rawDescData = file_mq_consume_user_proto_rawDesc
)

func file_mq_consume_user_proto_rawDescGZIP() []byte {
	file_mq_consume_user_proto_rawDescOnce.Do(func() {
		file_mq_consume_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_mq_consume_user_proto_rawDescData)
	})
	return file_mq_consume_user_proto_rawDescData
}

var file_mq_consume_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mq_consume_user_proto_goTypes = []any{
	(*MqUserInfo)(nil), // 0: mq_consume.MqUserInfo
}
var file_mq_consume_user_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mq_consume_user_proto_init() }
func file_mq_consume_user_proto_init() {
	if File_mq_consume_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mq_consume_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mq_consume_user_proto_goTypes,
		DependencyIndexes: file_mq_consume_user_proto_depIdxs,
		MessageInfos:      file_mq_consume_user_proto_msgTypes,
	}.Build()
	File_mq_consume_user_proto = out.File
	file_mq_consume_user_proto_rawDesc = nil
	file_mq_consume_user_proto_goTypes = nil
	file_mq_consume_user_proto_depIdxs = nil
}
