// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package mq_consume

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsUnspecified(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UNSPECIFIED.String() && e.Code == 500
}

func ErrorUnspecified(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UNSPECIFIED.String(), fmt.Sprintf(format, args...))
}

func IsUserAccountMissing(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USER_ACCOUNT_MISSING.String() && e.Code == 400
}

func ErrorUserAccountMissing(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_USER_ACCOUNT_MISSING.String(), fmt.Sprintf(format, args...))
}
