server:
  http:
    addr: 127.0.0.1:8000
    timeout: 1s
  grpc:
    addr: 127.0.0.1:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  rabbitmq:
    addrs:
      - amqp://root:root@127.0.0.1:5672/
    codec: json
    exchange: kratos
trace:
  endpoint: 127.0.0.1:4317