// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"kratos-project/app/grpc_user/internal/data/ent/article"
	"kratos-project/app/grpc_user/internal/data/ent/schema"
	"kratos-project/app/grpc_user/internal/data/ent/userinfo"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	articleMixin := schema.Article{}.Mixin()
	articleMixinHooks0 := articleMixin[0].Hooks()
	article.Hooks[0] = articleMixinHooks0[0]
	articleMixinInters0 := articleMixin[0].Interceptors()
	article.Interceptors[0] = articleMixinInters0[0]
	userinfoMixin := schema.UserInfo{}.Mixin()
	userinfoMixinHooks0 := userinfoMixin[0].Hooks()
	userinfo.Hooks[0] = userinfoMixinHooks0[0]
	userinfoMixinInters0 := userinfoMixin[0].Interceptors()
	userinfo.Interceptors[0] = userinfoMixinInters0[0]
}

const (
	Version = "v0.14.1"                                         // Version of ent codegen.
	Sum     = "h1:fUERL506Pqr92EPHJqr8EYxbPioflJo6PudkrEA8a/s=" // Sum of ent codegen.
)
