// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type Article struct {
	ent.Schema
}

func (Article) Fields() []ent.Field {
	return []ent.Field{field.Int("id").Comment("文章ID"), field.String("title").Comment("文章标题"), field.String("content").Comment("文章内容"), field.Time("created_at").Comment("创建时间"), field.Time("updated_at").Comment("更新时间"), field.Time("deleted_at").Optional().Comment("删除时间")}
}
func (Article) Edges() []ent.Edge {
	return nil
}
func (Article) Annotations() []schema.Annotation {
	return nil
}

// Mixin of the Article.
func (Article) Mixin() []ent.Mixin {
	return []ent.Mixin{
		SoftDeleteMixin{},
	}
}
